### ISSUE TITLE
Segmentation fault on restore tests with moodle-plugin-ci and PHP8.1

### ISSUE THREAD

**Issue by Glutamat42** [moodlehq/moodle-plugin-ci#204] opened 2023-02-23 10:15 UTC
I'm getting random Segfaults when running the tests for the restore logic with moodle-plugin-ci and PHP 8.1. It's not happening with PHP 7.4 and it's not happening if I phpunit directly.

Randomly means it happens most of the time, but not always. I could not see a scheme. For example here are two runs with basically the same code, [one is failing](https://github.com/ProjektAdLer/MoodlePlugin/actions/runs/4242337502) the [other one](https://github.com/ProjektAdLer/MoodlePlugin/actions/runs/4242257059) not.

I think it might be related to the `require_once($CFG->dirroot . '/backup/util/includes/restore_includes.php');` statement (or maybe `require_once($CFG->dirroot . '/local/adler/backup/moodle2/restore_local_adler_plugin.class.php');`) because it happens on every testcase in that file even on relatively simple ones like `test_define_module_plugin_structure`. I ran pipelines with only one of these tests enabled and for every one of these pipelines I got segfaults. Only way to avoid segfaults was to disable all tests in that file.

The test-file is available [here](https://github.com/ProjektAdLer/MoodlePlugin/blob/927dc3a3ef28e0f6af39dd9585ecaa68e8081c46/tests/backup/moodle2/restore_local_adler_plugin_test.php). Only relevant difference to the one used during the tests is that 
```
require_once($CFG->dirroot . '/backup/util/includes/restore_includes.php');
require_once($CFG->dirroot . '/local/adler/backup/moodle2/restore_local_adler_plugin.class.php');
```
were in the `SetUp` method. I don't have that exact file anymore because I squashed the commits.

The pipeline file with the workaround (using phpunit) is [this one](https://github.com/ProjektAdLer/MoodlePlugin/blob/927dc3a3ef28e0f6af39dd9585ecaa68e8081c46/.github/workflows/moodle-ci.yml). The moodle-plugin-ci command I used before is still there as a comment.

**Comment by stronk7** [comment] 2023-03-08 18:29
Hi,

have you tried running the very same but without the code coverage options?

I think that there are high chances of that being the problem in your jobs.

Note that moodle-plugin-ci, automatically, tries the best code coverage extension available in the environment, more specifically, it t looks for `pcov => xdebug => phpdbg`. See the [changelog](https://moodlehq.github.io/moodle-plugin-ci/CHANGELOG.html#330---2022-06-28) for more info.

And, looking to your workflow file… it seems that you don’t have neither pcov or xdebug installed. Hence phpdbg is used. And it’s really buggy since PHP 8.0 (in fact, I think that they are going to remove it from new versions, if haven’t done that already).

So, once you've verified that it's code coverage the cause of your random problems... all you've to do is to ensure that any of `pcov` or `xdebug` are installed. That's achieved with something like:

```
    - name: Setup PHP X.Y
      uses: shivammathur/setup-php@v2
      with:
        php-version: X.Y
        # We want to verify that xdebug works for coverage. Once we only support
        # Moodle 3.10/PHPUnit 8 and up, we can switch our tests to pcov too.
        coverage: xdebug
```

And that's the story, `phpdbg` is absolute evil, and I've seen it leading to those random crashes. So I hope the above will fix your problem.

Ciao :-)

**Comment by jrchamp** [comment] 2023-03-08 18:47
Hi @stronk7 

In the gha.dist.yml file, it seems like the default/"recommended" setting is `none`:
https://github.com/moodlehq/moodle-plugin-ci/blob/f1bf46eebd0060d590266cf40c321a1fb228f720/gha.dist.yml#L49-L50

Is that a misunderstanding? Does moodle-plugin-ci always check code coverage? If so, would it be better to have the default be set to `xdebug`?

**Comment by stronk7** [comment] 2023-03-09 11:11
Hi @Glutamat42 ,

I'm proceeding to close this. The explanations about why you are getting those seg faults are above and I think that moving to another (xdebug, pcov) alternative will fix them. And now the docs (thanks @jrchamp !) explain it better.

Don't hesitate to create another issue if the problems persist, thanks!

**Closed by stronk7** 2023-03-09 11:11 UTC
